### PR TITLE
Try 3 Overwrite Problem

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by JavierLeon9966** [comment]
Why you created this PR?
I need more information about what are you trying to do

**Comment by ghost** [comment]
Because he say two Errors to me


RuntimeException: "Trying to overwrite an already registered block" (EXCEPTION) in "pmsrc/src/pocketmine/block/BlockFactory" at line 370

[01:11:29] [Server thread/CRITICAL]: #0 plugins/ExtendedBlocks_dev-33.phar/src/JavierLeon9966/ExtendedBlocks/Main(89): pocketmine\block\BlockFactory::registerBlock(object JavierLeon9966\ExtendedBlocks\block\CustomBlock)



And

InvalidArgumentException: "Unmapped ID/metadata combination 526:0" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/convert/ItemTranslator" at line 149

[00:16:17] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream(262): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkId(integer 526, integer 0)

**Comment by ghost** [comment]
The overwrite problem comes from Main line 89 but i looked in TableSpoon and he use for register the Block

Example from TableSpoon 
BlockFactory:: registerBlock(new NetheriteBlock(), true);

Your Block registration dosent overwrite the positives Items if i give me NetheriteBlock 525 what ever the ID he give me a Internal Server Error and say me unmapped Block

You but a Config i written a new block but dosent work @JavierLeon9966

**Comment by JavierLeon9966** [comment]
Just don’t register the Netherite Block in config, that’s the problem and to get the item don’t do `/give Dragon 525` is `/give Dragon -270`

**Pull request closed without merging**
